# This config supports using placeholders.
# options are <git_hash> <commit_message> <me> <today> <yyyymmdd> <time> <pwd>
# and all keys from your local 'machine_specific_paths.toml' as well as 'io'
# and top layer dictionary entries

visualize = true              # whether to save image/video visualizations of detectors
save_csv = true               # whether to save all results to csv-files

error_level = "DETECTOR"      # Options: "DETECTOR", "SEQUENCE", "STRICT" (from least to most strict)
log_level = "INFO"            # Options: "CRITICAL", "ERROR", "WARNING", "INFO", "DEBUG"

# checks that all detectors have their input dependencies enabled
check_missing_detectors_dependencies = true 

# each component can be assigned to / run with multiple different algorithms
[component_algorithm_mapping]
gaze_individual = ['multiview_eth_xgaze']
gaze_multiview = ['gaze_fusion']
gaze_interaction = ['gaze_distance']
body_joints = ['hrnetw48', 'vitpose_huge', 'rtmpose_l_wholebody', 'rtmpose_m_mpii', 'sam_3d_body']
body_joints_local = ['sam_3d_body', 'motionbert']
body_mesh = ['sam_3d_body']
hand_joints = ['hrnetw48', 'rtmpose_l_wholebody']
face_landmarks = ['hrnetw48', 'rtmpose_l_wholebody']
kinematics = ['velocity_body']
proximity = ['body_distance']
emotion_individual = ['py_feat']
head_orientation = ['spiga']
audio_transcription = ['whisperx']
audio_diarization = ['whisperx']
speaker_aligned_transcription = ['whisperx']

# define which data to run on
[run]
[run.communication_multiview]
components = [
   "audio_transcription", "audio_diarization", "speaker_aligned_transcription",
   "body_joints", "body_joints_local", "body_mesh",
   "gaze_individual", "gaze_multiview", "gaze_interaction", 
   "kinematics", "proximity", "emotion_individual", "head_orientation"
]
videos = [
   {session_ID = "", sequence_ID="sequence_xyz", video_start = 0, video_length = -1}  # Note: -1 for full video length
]

[io]
experiment_name = "<yyyymmdd>"                                     # define the name of the experiment (str), default: date as "<yyyymmdd>"
out_folder = "<output_folder_path>/experiments/<experiment_name>"  # define where to save the experiment output (str)
# Output folders based on the video (with video level placeholders)
out_sub_folder_name = "<cur_dataset_name>_<cur_session_ID>_<cur_sequence_ID>_s<cur_video_start>_l<cur_video_length>"
out_sub_folder = "<out_folder>/<out_sub_folder_name>"
csv_out_folder = "<out_sub_folder>/_csv_files"
# Preprocessed data input folder for Nicetoolbox format
nicetoolbox_input_folder = "<output_folder_path>/nicetoolbox_input/<cur_dataset_name>_<cur_session_ID>_<cur_sequence_ID>"
# Code, assets and config file paths
code_folder = "<pwd>"
assets = "<code_folder>/nicetoolbox/detectors/assets"
asset_manifest = "<code_folder>/configs/asset_manifest.toml" # this config is in the NICE installation, not project!
dataset_properties = "<configs_folder_path>/dataset_properties.toml"
detectors_config = "<configs_folder_path>/detectors_config.toml"
predictions_mapping = "<configs_folder_path>/predictions_mapping.toml"
# Below are output folders with placeholders for current component and algorithm names
detector_folder = "<out_sub_folder>/<cur_component_name>/<cur_algorithm_name>"
detector_out_folder = "<detector_folder>/detector_output"
detector_visualization_folder = "<detector_folder>/visualization"
detector_additional_output_folder = "<detector_folder>/additional_output"
detector_run_config_path = "<detector_folder>"
detector_final_result_folder = "<out_sub_folder>/<cur_component_name>"
